### ISSUE TITLE
Convert Shelve to HDF5 

### ISSUE THREAD

**Issue by szwiep** [szwiep/py_BeLT#11]
Python Shelve is not appearing to be platform cross-compatible and is not necessarily well suited to the amount of data that a long Py_BeRCM run produces. The HDF5 format should be better suited to the model.
The validity of HDF5 format should be investigated further before this issue is addressed via a new feature.

**Comment by szwiep** [comment]
Addressed in 52237c0

**Comment by smchartrand** [comment]
just sent a message to JOSS about the pdf preview problem through Whedon...

________________________________
